using System;

namespace Domain;

public class Reservation
{
    public string Id { get; set; } = Guid.NewGuid().ToString(); //autogenerated unique ID. a string, EF will recognize this is key

    public required string Ime { get; set; }

    public required string Usluga { get; set; }

    public DateTime DateTime { get; set; }

    public required string Email { get; set; }

    public required string BrojMobitela { get; set; }

    public string? Napomena { get; set; }

}
